version: '3.8'
volumes:
  db_data:

services:
  db_events:
    container_name: db_events
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql

  web_event_build:
    image: web_event_build
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql

  web_event:
    image: web_event_build
    container_name: web_event_build
    depends_on:
      - web_event_build
      - db_events
    environment:
      POSTGRES_HOST: db_event
    env_file:
      - .env
    ports:
      - 3002:3002
    command: /app/bin/dev
    volumes:
      - ./:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.space_web.rule=Host(`${WEB_EVENT_HOST}`)"
      - "traefik.http.services.space_web.loadbalancer.server.port=3002"